Repository LostArtefacts/TRX, pull requests merged in 2021-12, with the labels that each got.

#260 makefile: use bash for the lint command
  Makefile
Labels: Internal

#265 demo: fix crash if user inputs during demo ring close
  src/game/inventry.c
Labels: T1M bug

#263 Bridge grab fix
  README.md
  bin/cfg/Tomb1Main.json5
  src/config.c
  src/config.h
  src/game/control_util.c
  src/game/lara.c
  src/game/objects/bridge.c
  src/game/objects/bridge.h
Labels: OG bug

#258 alligator: fix alligator dealing no damage if Lara is still
  README.md
  bin/cfg/Tomb1Main.json5
  src/config.c
  src/config.h
  src/game/ai/alligator.c
  src/game/ai/alligator.h
Labels: OG bug

#184 lara: fix shotgun shooting when target out of sight.
  README.md
  bin/cfg/Tomb1Main.json5
  src/config.c
  src/config.h
  src/game/lara1gun.c
Labels: Feature

#267 ui: fix default healthbar and airbar behavior
  bin/cfg/Tomb1Main.json5
  src/config.c
  src/config.h
  src/game/control.c
  src/game/invfunc.c
  src/game/overlay.c
  src/game/overlay.h
  src/game/setup.c
  src/global/vars.c
  src/global/vars.h
Labels: T1M bug

#276 savegame: fix loading legacy Evil Lara
  src/game/savegame.c
Labels: T1M bug, OG bug
