Repository LostArtefacts/TRX, pull requests merged in 2022-12, with the labels that each got.

#655 save_crystal: fixed to be single use and added collision
  CHANGELOG.md
  src/game/objects/general/save_crystal.c
  src/game/savegame/savegame.c
Labels: T1M bug

#658 Add reset and unbind options to the controls menu
  CHANGELOG.md
  README.md
  bin/cfg/Tomb1Main_gameflow.json5
  bin/cfg/Tomb1Main_gameflow_ub.json5
  src/config.h
  src/game/gameflow.c
  src/game/input.c
  src/game/input.h
  src/game/option/option_control.c
  src/game/overlay.c
  src/game/overlay.h
  src/game/text.c
  src/game/text.h
  src/global/const.h
  src/global/types.h
  src/init.c
  src/specific/s_input.c
  src/specific/s_input.h
Labels: Feature

#661 game_demo: fix demo mode if do not heal on level finish is used
  CHANGELOG.md
  src/game/game/game_demo.c
Labels: T1M bug

#665 config: French localization
  CHANGELOG.md
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/fr.json
  tools/config/Tomb1Main_ConfigTool/Tomb1Main_ConfigTool.csproj
Labels: Feature

#662 input: stop the default controls from functioning when unbound
  CHANGELOG.md
  README.md
  src/game/input.c
  src/game/input.h
  src/game/option/option_control.c
  src/specific/s_input.c
Labels: Feature

#676 Fix support for 64-bit
  src/game/level.c
  src/global/types.h
Labels: Internal

#674 option_control: added customizable controller support
  CHANGELOG.md
  README.md
  bin/cfg/Tomb1Main_gameflow.json5
  bin/cfg/Tomb1Main_gameflow_ub.json5
  meson.build
  src/config.c
  src/config.h
  src/game/gameflow.c
  src/game/input.c
  src/game/input.h
  src/game/option/option.c
  src/game/option/option_control.c
  src/game/option/option_control.h
  src/game/option/option_control_pick.c
  src/game/option/option_control_pick.h
  src/game/text.c
  src/global/types.h
  src/init.c
  src/specific/s_input.c
  src/specific/s_input.h
Labels: Feature
