Repository LostArtefacts/TRX, pull requests merged in 2022-02, with the labels that each got.

#381 Fix detail levels text flashing
  CHANGELOG.md
  README.md
  src/config.h
  src/game/option_graphics.c
  src/specific/s_input.c
Labels: OG bug

#391 cinema: fix cutscene last frame
  CHANGELOG.md
  src/game/cinema.c
Labels: T1M bug

#394 s/fmv: do not free up game memory
  CHANGELOG.md
  src/specific/s_fmv.c
Labels: T1M bug

#397 inv: fix fade ending one frame too early
  src/game/inventry.c
Labels: T1M bug

#400 game: fix title menu resuming music after demo when minimized
  CHANGELOG.md
  src/game/game.c
Labels: T1M bug

#403 inv: fix black frame after saving
  src/game/inventry.c
Labels: T1M bug

#404 ai/pod: spawn only objects that are loaded
  CHANGELOG.md
  README.md
  src/game/ai/pod.c
Labels: OG bug

#387 compass: add total number of pickups and killables
  CHANGELOG.md
  README.md
  bin/cfg/Tomb1Main_gameflow.json5
  bin/cfg/Tomb1Main_gameflow_ub.json5
  meson.build
  src/game/ai/baldy.c
  src/game/ai/cowboy.c
  src/game/ai/skate_kid.c
  src/game/control.h
  src/game/control_util.c
  src/game/game.c
  src/game/gameflow.c
  src/game/gameflow.h
  src/game/larafire.c
  src/game/level.c
  src/game/option_compass.c
  src/game/savegame.c
  src/game/setup.c
  src/game/stats.c
  src/game/stats.h
  src/global/types.h
  src/init.c
Labels: Feature

#407 game: fix gun pickups disappearing on save load
  CHANGELOG.md
  README.md
  src/game/game.c
  src/game/savegame.c
  src/game/savegame.h
  src/game/savegame_bson.c
Labels: OG bug

#411 s/output: fix drawing floor in cutscene 4
  CHANGELOG.md
  bin/cfg/Tomb1Main_gameflow.json5
  src/specific/s_output.c
Labels: T1M bug

#413 lara: make starting health configurable
  CHANGELOG.md
  README.md
  bin/cfg/Tomb1Main.json5
  src/config.c
  src/config.h
  src/game/laramisc.c
  src/game/overlay.c
  src/game/savegame.c
  src/game/savegame_bson.c
  src/game/setup.c
Labels: Feature

#426 option/compass: change text order
  CHANGELOG.md
  src/game/option_compass.c
  src/game/stats.c
Labels: T1M bug

#425 gameflow: fix Lara losing her pistols forever
  CHANGELOG.md
  bin/cfg/Tomb1Main_gameflow.json5
  src/game/gameflow.c
  src/global/types.h
Labels: T1M bug

#430 Dart hit effect
  CHANGELOG.md
  README.md
  src/game/traps/dart.c
Labels: OG bug

#193 inv: add ability to restart level from passport when Lara dies
  CHANGELOG.md
  README.md
  bin/cfg/Tomb1Main_gameflow.json5
  bin/cfg/Tomb1Main_gameflow_ub.json5
  src/game/game.c
  src/game/gameflow.c
  src/game/inventry.c
  src/game/option_passport.c
  src/global/types.h
  src/global/vars.c
  src/global/vars.h
  src/init.c
Labels: Feature
