Repository LostArtefacts/TRX, pull requests merged in 2022-05, with the labels that each got.

#534 savegame: changed savegame requestor to remember requested
  CHANGELOG.md
  src/game/savegame.c
Labels: Feature

#494 option_passport: add level selection to the load game menu
  CHANGELOG.md
  README.md
  bin/cfg/Tomb1Main_gameflow.json5
  bin/cfg/Tomb1Main_gameflow_ub.json5
  src/game/demo.c
  src/game/game.c
  src/game/gameflow.c
  src/game/inventry.c
  src/game/lara/lara.c
  src/game/objects/save_crystal.c
  src/game/option_passport.c
  src/game/savegame.c
  src/game/savegame.h
  src/game/savegame_bson.c
  src/game/savegame_bson.h
  src/game/savegame_legacy.c
  src/game/savegame_legacy.h
  src/game/shell.c
  src/global/types.h
  src/init.c
Labels: Feature

#537 savegame: fix pushables loading for legacy savegames
  CHANGELOG.md
  src/game/savegame_legacy.c
Labels: T1M bug

#548 passport: fix passport menu with high UI scaling
  CHANGELOG.md
  src/game/option_passport.c
Labels: T1M bug

#549 Requestor bottom row off by one pixel
  CHANGELOG.md
  src/game/output.c
Labels: T1M bug

#566 pickup: fix Lara not picking up items near room portals
  CHANGELOG.md
  src/game/objects/pickup.c
Labels: T1M bug

#567 passport: fix new game and save game using wrong closing animation
  CHANGELOG.md
  src/game/option/option_passport.c
Labels: T1M bug

#569 Fix bridges embedding under the floor
  CHANGELOG.md
  README.md
  src/game/objects/general/bridge.c
  src/game/objects/general/bridge.h
Labels: OG bug

#568 s/input: add SDL controller support
  CHANGELOG.md
  README.md
  src/specific/s_input.c
Labels: Feature

#570 gameflow: add stats screen and fade out to Lara's Home
  CHANGELOG.md
  bin/cfg/Tomb1Main_gameflow.json5
  src/game/stats.c
Labels: Feature

#572 savegame: fixed Lara's outfit in Lara's Home when replaying the level
  CHANGELOG.md
  src/game/game/game.c
  src/game/inventory/inventory.c
  src/game/shell.c
  src/global/types.h
Labels: T1M bug

#576 savegame: fix death counter
  CHANGELOG.md
  src/game/inventory/inventory.c
  src/game/option/option_passport.c
Labels: T1M bug

#578 shell: option_init needs gameflow to be loaded first
  src/game/shell.c
Labels: T1M bug, Internal
