Repository LostArtefacts/TRX, pull requests merged in 2022-01, with the labels that each got.

#282 lara: fix hang bug for stacked rooms
  README.md
  src/game/lara.c
Labels: OG bug

#285 output: improve VBuf fidelity
  src/game/output.c
  src/global/types.h
Labels: OG bug

#290 fix save crystal mode saving before gym level
  src/game/gameflow.c
Labels: T1M bug

#292 s/output: clear picture surface before blit
  src/specific/s_output.c
Labels: T1M bug

#291 gfx: remove tiny resolutions
  src/global/vars.c
Labels: Internal

#293 lava: fix Lara getting set on fire on trapdoors over Lava
  README.md
  src/game/traps/lava.c
Labels: OG bug

#294 gfx: fix garbage value resolutions showing as options
  src/global/const.h
Labels: T1M bug

#295 overlay: fix airbar showing on deaths outside of water
  src/game/overlay.c
Labels: T1M bug

#304 game: fix top offscreen load game selection
  src/game/game.c
Labels: T1M bug

#306 camera: make underwater sound effect ambient
  README.md
  src/game/camera.c
Labels: OG bug

#307 collide: fix Lara glitching through static objects into the void
  README.md
  src/game/collide.c
Labels: OG bug

#314 Load game offscreen selection fix
  src/game/game.c
Labels: T1M bug

#298 shell: save screenshots in a folder
  src/filesystem.c
  src/filesystem.h
  src/game/clock.c
  src/game/clock.h
  src/game/shell.c
  src/game/shell.h
  src/specific/s_filesystem.c
  src/specific/s_filesystem.h
Labels: Feature

#313 input: allow holding down forward/back to move through saves
  src/game/input.c
Labels: Feature

#319 inventory: fix black screen frames when switching inventory
  README.md
  src/game/inventry.c
  src/game/output.c
  src/game/output.h
  src/gfx/3d/3d_renderer.c
  src/gfx/3d/3d_renderer.h
  src/specific/s_output.c
  src/specific/s_output.h
Labels: OG bug

#320 control_pause: fix ambient noises not pausing on pause screen
  src/game/control_pause.c
Labels: T1M bug

#311 music: fix secret chime when collecting consecutive secrets if no fix
  src/game/music.c
  src/global/types.h
Labels: T1M bug

#328 gfx: fix crash when shader compilation fails
  src/gfx/3d/3d_renderer.c
  src/specific/s_output.c
Labels: T1M bug

#329 bin: downgrade shaders to GLSL version 1.30
  bin/shaders/2d.fsh
  bin/shaders/2d.vsh
  bin/shaders/3d.fsh
  bin/shaders/3d.vsh
Labels: Feature

#341 s/fmv: let players skip FMVs with the action key
  README.md
  src/specific/s_fmv.c
Labels: Feature

#342 log: place Tomb1Main.log in the game directory
  src/log.c
Labels: T1M bug

#343 picture: simplify memory management
  src/game/output.c
  src/game/picture.c
  src/game/picture.h
  src/gfx/screenshot.c
  src/specific/s_output.c
  src/specific/s_picture.c
  src/specific/s_picture.h
Labels: Internal

#345 movable_block: fix pushing blocks through doors
  README.md
  src/game/collide.c
  src/game/traps/movable_block.c
Labels: OG bug

#350 s_shell: mute all sound when game is minimized
  README.md
  src/specific/s_shell.c
Labels: OG bug

#351 Support DPI scaling on Windows
  src/specific/s_shell.c
Labels: OG bug

#335 gameflow: fix fallback game strings not working
  scripts/generate_init
  src/game/gameflow.c
  src/game/gameflow.h
  src/game/shell.c
  src/init.c
  src/init.h
Labels: Internal

#360 input: fix certain inputs skipping too many things
  src/game/cinema.c
  src/game/control.c
  src/game/game.c
  src/game/shell.c
  src/specific/s_fmv.c
Labels: T1M bug

#368 output: add fade animations
  README.md
  bin/cfg/Tomb1Main.json5
  src/config.c
  src/config.h
  src/game/control_pause.c
  src/game/demo.c
  src/game/draw.c
  src/game/draw.h
  src/game/game.c
  src/game/gameflow.c
  src/game/inventry.c
  src/game/output.c
  src/game/output.h
  src/game/shell.c
  src/gfx/3d/3d_renderer.c
  src/gfx/3d/3d_renderer.h
  src/specific/s_output.c
  src/specific/s_output.h
Labels: Feature

#377 option_graphics: make vsync optional from glasses menu
  CHANGELOG.md
  README.md
  bin/cfg/Tomb1Main_gameflow.json5
  bin/cfg/Tomb1Main_gameflow_ub.json5
  src/config.h
  src/game/gameflow.c
  src/game/option_graphics.c
  src/game/settings.c
  src/gfx/context.c
  src/gfx/context.h
  src/global/types.h
  src/init.c
Labels: Feature
