Repository LostArtefacts/TRX, pull requests merged in 2022-04, with the labels that each got.

#507 pickup: add ability to pick up multiple items with walk to items
  CHANGELOG.md
  src/game/objects/pickup.c
Labels: Feature

#508 camera: adhere to naming convention
  src/game/camera.c
  src/game/camera.h
  src/game/control.c
  src/game/game.c
  src/game/laramisc.c
Labels: Internal

#502 Refactor savegames to use start and current info
  CHANGELOG.md
  src/game/control.c
  src/game/demo.c
  src/game/game.c
  src/game/gameflow.c
  src/game/inventry.c
  src/game/lara.h
  src/game/larafire.c
  src/game/laramisc.c
  src/game/objects/pickup.c
  src/game/objects/scion.c
  src/game/option_compass.c
  src/game/overlay.c
  src/game/savegame.c
  src/game/savegame.h
  src/game/savegame_bson.c
  src/game/savegame_common.h
  src/game/savegame_legacy.c
  src/game/setup.c
  src/game/shell.c
  src/game/stats.c
  src/global/types.h
Labels: Help wanted, Feature, Internal

#509 s_clock: add a cheat to increase the game speed
  CHANGELOG.md
  README.md
  bin/cfg/Tomb1Main_gameflow.json5
  bin/cfg/Tomb1Main_gameflow_ub.json5
  src/game/clock.c
  src/game/clock.h
  src/game/gameflow.c
  src/game/input.c
  src/game/laramisc.c
  src/game/option_control.c
  src/global/types.h
  src/init.c
  src/specific/s_clock.c
  src/specific/s_input.c
Labels: Feature

#515 passport: create enums for g_InvExtraData
  src/game/game.c
  src/game/inventry.c
  src/game/objects/save_crystal.c
  src/game/option_passport.c
  src/global/types.h
Labels: Internal

#516 passport: add select level requestor
  bin/cfg/Tomb1Main_gameflow.json5
  bin/cfg/Tomb1Main_gameflow_ub.json5
  src/game/game.c
  src/game/gameflow.c
  src/game/inventry.c
  src/game/option_passport.c
  src/game/savegame.c
  src/game/savegame.h
  src/global/types.h
  src/global/vars.h
  src/init.c
Labels: Internal

#518 matrix: add a matrix stack overflow error check and crash message
  CHANGELOG.md
  src/3dsystem/matrix.c
  src/game/draw.c
  src/game/draw.h
Labels: OG bug
