Repository LostArtefacts/TRX, pull requests merged in 2022-08, with the labels that each got.

#608 inventory: kill SFX in inventory with disable_music_in_inventory
  CHANGELOG.md
  src/game/inventory/inventory.c
Labels: T1M bug

#601 savegame: added FX, lava emitters, flame emitters, and waterfalls
  CHANGELOG.md
  README.md
  bin/cfg/Tomb1Main.json5
  src/config.c
  src/config.h
  src/game/objects/effects/waterfall.c
  src/game/objects/traps/flame.c
  src/game/objects/traps/lava.c
  src/game/savegame.h
  src/game/savegame/savegame_bson.c
  src/game/savegame/savegame_legacy.c
Labels: Feature

#598 fixed underwater currents breaking in rare cases
  CHANGELOG.md
  README.md
  src/game/lara/lara_control.c
  src/game/savegame/savegame.c
  src/game/savegame/savegame_legacy.c
Labels: OG bug

#613 option_passport: fix save crystal mode saving in the first slot
  CHANGELOG.md
  src/game/option/option_passport.c
Labels: T1M bug

#614 gameflow: add remove_ammo and remove_medipacks options
  CHANGELOG.md
  src/game/gameflow.c
  src/game/lara/lara.c
  src/global/types.h
Labels: Feature
