Repository LostArtefacts/TRX, pull requests merged in 2022-03, with the labels that each got.

#451 pickup: add ability to walk to pickups when nearby
  CHANGELOG.md
  README.md
  bin/cfg/Tomb1Main.json5
  src/config.c
  src/config.h
  src/game/collide.c
  src/game/collide.h
  src/game/lara.c
  src/game/lara.h
  src/game/laramisc.c
  src/game/objects/pickup.c
  src/game/objects/pickup.h
  src/game/objects/savegame_crystal.c
  src/global/types.h
Labels: Feature

#452 switch: add option to walk to switches when nearby
  CHANGELOG.md
  src/game/objects/switch.c
  src/game/objects/switch.h
Labels: Feature

#453 stats: let users revert back to basic stats
  CHANGELOG.md
  bin/cfg/Tomb1Main.json5
  bin/cfg/Tomb1Main_gameflow.json5
  src/config.c
  src/config.h
  src/game/gameflow.c
  src/game/option_compass.c
  src/game/stats.c
  src/global/types.h
  src/init.c
Labels: Feature

#455 pod: fix pods unhatching on reload if user saves during explosion
  CHANGELOG.md
  README.md
  src/game/ai/pod.c
Labels: OG bug

#456 text: add left/right arrow support and new text functions
  src/game/text.c
  src/game/text.h
Labels: Internal

#458 option_passport: add contextual arrows and clean up
  CHANGELOG.md
  src/game/option_passport.c
Labels: Feature

#460 option_sound: add contextual arrows
  CHANGELOG.md
  src/game/option_sound.c
  src/global/types.h
Labels: Feature

#463 option_control: add contextual arrows
  CHANGELOG.md
  src/game/option_control.c
Labels: Feature

#469 Add final stats screen
  CHANGELOG.md
  README.md
  bin/cfg/Tomb1Main.json5
  bin/cfg/Tomb1Main_gameflow.json5
  src/config.c
  src/config.h
  src/game/gameflow.c
  src/game/stats.c
  src/game/stats.h
  src/global/types.h
Labels: Feature

#473 option_graphics: offset title bar to match other menus
  src/game/option_graphics.c
Labels: T1M bug

#474 gameflow: add music to credits
  CHANGELOG.md
  README.md
  bin/cfg/Tomb1Main_gameflow.json5
  bin/cfg/Tomb1Main_gameflow_ub.json5
Labels: Feature

#471 gameflow: add support for unobtainable pickups and kills
  CHANGELOG.md
  README.md
  bin/cfg/Tomb1Main_gameflow.json5
  bin/cfg/Tomb1Main_gameflow_ub.json5
  src/game/gameflow.c
  src/game/gameflow.h
  src/game/stats.c
Labels: Feature

#475 gamflow_ub: add stats screen to the end of Unfinished Business
  bin/cfg/Tomb1Main_gameflow_ub.json5
Labels: Feature

#477 option_sound: fix rapid sound effect if input held down
  CHANGELOG.md
  README.md
  src/game/option_sound.c
Labels: T1M bug

#485 option_graphics: fix not using gameflow strings
  bin/cfg/Tomb1Main_gameflow.json5
  bin/cfg/Tomb1Main_gameflow_ub.json5
  src/game/gameflow.c
  src/game/stats.c
  src/global/types.h
  src/init.c
Labels: T1M bug

#487 inventry: add the option to pause sound in the inventory
  CHANGELOG.md
  README.md
  bin/cfg/Tomb1Main.json5
  src/config.c
  src/config.h
  src/game/inventry.c
Labels: Feature

#489 output: fix ghost margins during fades
  CHANGELOG.md
  src/game/output.c
Labels: T1M bug

#493 stats: stop all music after final statistics are displayed
  CHANGELOG.md
  src/game/stats.c
Labels: T1M bug

#498 gamflow_ub: fix UB not using new stats strings
  CHANGELOG.md
  bin/cfg/Tomb1Main_gameflow_ub.json5
Labels: T1M bug

#501 pickup: fix multiple underwater pickups with walk_to_items
  CHANGELOG.md
  src/game/objects/pickup.c
Labels: T1M bug
