Repository LostArtefacts/TRX, pull requests merged in 2023-10, with the labels that each got.

#1022 data: rotate the Scion to face Qualopec main gate
  CHANGELOG.md
  bin/data/qualopec_itemrots.bin
Labels: Data, Enhancement

#1023 game: add an option to enable frame buffering
  CHANGELOG.md
  src/config.c
  src/config.h
  src/game/game/game.c
  tools/config/TR1X_ConfigTool/Resources/Lang/en.json
  tools/config/TR1X_ConfigTool/Resources/Lang/fr.json
  tools/config/TR1X_ConfigTool/Resources/specification.json
Labels: Feature

#1024 Added spanish translation for enable_buffering
  tools/config/TR1X_ConfigTool/Resources/Lang/es.json
Labels: Feature

#1020 docs: expand on gameflow usage
  CHANGELOG.md
  CONTRIBUTING.md
  GAMEFLOW.md
  README.md
  bin/cfg/TR1X_gameflow.json5
  bin/cfg/TR1X_gameflow_ub.json5
Labels: Enhancement

#1025 items: use relative frames for more anim switches
  src/game/game/game_cutscene.c
  src/game/items.c
  src/game/items.h
  src/game/objects/common.c
  src/game/objects/creatures/bacon_lara.c
  src/game/objects/creatures/bat.c
  src/game/objects/creatures/skate_kid.c
  src/game/objects/creatures/torso.c
  src/game/objects/creatures/trex.c
  src/game/objects/general/scion.c
  src/game/objects/traps/midas_touch.c
  src/game/objects/traps/thors_hammer.c
Labels: Internal

#1028 midas: add pickup overlay for gold bar
  CHANGELOG.md
  src/game/objects/traps/midas_touch.c
Labels: Enhancement

#1032 ai: extend item drop support to all enemies
  GAMEFLOW.md
  src/game/carrier.c
  src/game/carrier.h
  src/game/items.c
  src/game/objects/creatures/crocodile.c
  src/game/objects/creatures/mutant.c
  src/game/objects/creatures/rat.c
  src/game/savegame/savegame_bson.c
  src/global/types.h
Labels: Enhancement

#1033 creature: fix dead water creature placement
  CHANGELOG.md
  src/game/creature.c
  src/game/creature.h
  src/game/items.c
  src/game/objects/creatures/crocodile.c
  src/game/objects/creatures/rat.c
Labels: OG bug

#1039 lara: enable lean jumping
  CHANGELOG.md
  src/config.c
  src/config.h
  src/game/lara/lara_col.c
  tools/config/TR1X_ConfigTool/Resources/Lang/en.json
  tools/config/TR1X_ConfigTool/Resources/Lang/fr.json
  tools/config/TR1X_ConfigTool/Resources/specification.json
Labels: Feature

#1041 inventory: hardcode the passport and pickups FOV
  CHANGELOG.md
  src/game/camera.c
  src/game/effect_routines/lara_effects.c
  src/game/inventory/inventory.c
  src/game/level.c
  src/game/overlay.c
  src/game/screen.c
  src/game/viewport.c
  src/game/viewport.h
  src/global/const.h
Labels: TR1X bug

#1042 gfx: fix depth buffer issues with 3d pickups
  CHANGELOG.md
  src/gfx/3d/3d_renderer.c
Labels: TR1X bug

#1037 Gun frame tests
  meson.build
  src/game/anim.c
  src/game/anim.h
  src/game/gun/gun.c
  src/game/gun/gun_pistols.c
  src/game/gun/gun_rifle.c
  src/game/items.c
  src/global/types.h
Labels: Internal

#1047 config: add ability to disable the EIDOS logo
  CHANGELOG.md
  src/config.h
  src/config_map.c
  src/game/gameflow.c
  src/game/inventory/inventory.c
  src/game/shell.c
  src/global/types.h
  tools/config/TR1X_ConfigTool/Resources/Lang/en.json
  tools/config/TR1X_ConfigTool/Resources/Lang/es.json
  tools/config/TR1X_ConfigTool/Resources/Lang/fr.json
  tools/config/TR1X_ConfigTool/Resources/specification.json
Labels: Feature

#1049 tools: clean installer and config tool
  tools/config/TR1X_ConfigTool/App.xaml
  tools/config/TR1X_ConfigTool/App.xaml.cs
  tools/config/TR1X_ConfigTool/Controls/AboutWindow.xaml
  tools/config/TR1X_ConfigTool/Controls/AboutWindow.xaml.cs
  tools/config/TR1X_ConfigTool/Controls/CategoryControl.xaml
  tools/config/TR1X_ConfigTool/Controls/CategoryControl.xaml.cs
  tools/config/TR1X_ConfigTool/Controls/MainWindow.xaml
  tools/config/TR1X_ConfigTool/Controls/MainWindow.xaml.cs
  tools/config/TR1X_ConfigTool/Controls/NumericUpDown.xaml
  tools/config/TR1X_ConfigTool/Controls/NumericUpDown.xaml.cs
  tools/config/TR1X_ConfigTool/Controls/PropertyControl.xaml
  tools/config/TR1X_ConfigTool/Controls/PropertyControl.xaml.cs
  tools/config/TR1X_ConfigTool/Models/BaseLanguageViewModel.cs
  tools/config/TR1X_ConfigTool/Models/CategoryViewModel.cs
  tools/config/TR1X_ConfigTool/Models/Lang/Language.cs
  tools/config/TR1X_ConfigTool/Models/Lang/PropertyText.cs
  tools/config/TR1X_ConfigTool/Models/MainWindowViewModel.cs
  tools/config/TR1X_ConfigTool/Models/Specification/BaseProperty.cs
  tools/config/TR1X_ConfigTool/Models/Specification/Category.cs
  tools/config/TR1X_ConfigTool/Models/Specification/Configuration.cs
  tools/config/TR1X_ConfigTool/Models/Specification/DataType.cs
  tools/config/TR1X_ConfigTool/Models/Specification/EnumOption.cs
  tools/config/TR1X_ConfigTool/Models/Specification/Specification.cs
  tools/config/TR1X_ConfigTool/Models/Specification/Types/BoolProperty.cs
  tools/config/TR1X_ConfigTool/Models/Specification/Types/EnumProperty.cs
  tools/config/TR1X_ConfigTool/Models/Specification/Types/NumericProperty.cs
  tools/config/TR1X_ConfigTool/Resources/styles.xaml
  tools/config/TR1X_ConfigTool/TR1X_ConfigTool.csproj
  tools/config/TR1X_ConfigTool/Utils/AssemblyUtils.cs
  tools/config/TR1X_ConfigTool/Utils/BaseNotifyPropertyChanged.cs
  tools/config/TR1X_ConfigTool/Utils/BindingProxy.cs
  tools/config/TR1X_ConfigTool/Utils/Converters/BoolToVisibilityConverter.cs
  tools/config/TR1X_ConfigTool/Utils/Converters/ConditionalMarkupConverter.cs
  tools/config/TR1X_ConfigTool/Utils/Converters/ConditionalViewTextConverter.cs
  tools/config/TR1X_ConfigTool/Utils/Json/NumericConverter.cs
  tools/config/TR1X_ConfigTool/Utils/Json/PropertyConverter.cs
  tools/config/TR1X_ConfigTool/Utils/Json/PropertyResolver.cs
  tools/config/TR1X_ConfigTool/Utils/MessageBoxUtils.cs
  tools/config/TR1X_ConfigTool/Utils/NumericValidationRule.cs
  tools/config/TR1X_ConfigTool/Utils/ProcessUtils.cs
  tools/config/TR1X_ConfigTool/Utils/RelayCommand.cs
  tools/config/TR1X_ConfigTool/Utils/VisualUtils.cs
  tools/installer/Installer/Controls/InstallStepControl.xaml
  tools/installer/Installer/Controls/InstallStepControl.xaml.cs
  tools/installer/Installer/Installer.csproj
  tools/installer/Installer/Installers/GOGInstallSource.cs
  tools/installer/Installer/Installers/InstallExecutor.cs
  tools/installer/Installer/Installers/InstallUtils.cs
  tools/installer/Installer/Models/MainWindowViewModel.cs
  tools/installer/Installer/Utils/BinaryReaderExtensions.cs
  tools/installer/Installer/Utils/ConditionalMarkupConverter.cs
  tools/installer/Installer/Utils/CueFile.cs
  tools/installer/Installer/Utils/CueTrack.cs
  tools/installer/Installer/Utils/HttpProgressClient.cs
  tools/installer/Installer/Utils/RelayCommand.cs
  tools/installer/Installer/Utils/ShortcutUtils.cs
Labels: Internal

#1057 installer: add UB pack option
  CHANGELOG.md
  README.md
  tools/installer/Installer/Controls/InstallSettingsStepControl.xaml
  tools/installer/Installer/Installers/InstallExecutor.cs
  tools/installer/Installer/Models/InstallSettings.cs
  tools/installer/Installer/Models/UBPackType.cs
  tools/installer/Installer/Utils/ComparisonConverter.cs
Labels: Enhancement

#1059 sliding pillar: rename rolling block
  meson.build
  src/game/objects/traps/rolling_block.h
  src/game/objects/traps/sliding_pillar.c
  src/game/objects/traps/sliding_pillar.h
  src/game/room.c
  src/game/savegame/savegame.c
  src/game/setup.c
  src/global/types.h
Labels: Internal
