Repository LostArtefacts/TRX, pull requests merged in 2023-09, with the labels that each got.

#961 passport: fix new game plus if enable_game_modes set to false
  CHANGELOG.md
  src/game/option/option_passport.c
Labels: T1M bug

#959 effects: simplify linked lists management
  src/game/effects.c
  src/game/room_draw.c
  src/global/types.h
Labels: Internal

#964 config: move enable_game_modes to config and add gameflow override
  CHANGELOG.md
  bin/cfg/Tomb1Main_gameflow.json5
  bin/cfg/Tomb1Main_gameflow_ub.json5
  src/config.c
  src/config.h
  src/game/gameflow.c
  src/game/gameflow.h
  src/game/option/option_passport.c
  src/game/savegame/savegame_bson.c
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/en.json
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/fr.json
  tools/config/Tomb1Main_ConfigTool/Resources/specification.json
Labels: Feature

#970 savegame: prevent loading legacy FX data
  src/game/savegame/savegame_bson.c
Labels: T1M bug

#965 config: move enable_save_crystals to config; add override
  CHANGELOG.md
  bin/cfg/Tomb1Main_gameflow.json5
  bin/cfg/Tomb1Main_gameflow_ub.json5
  src/config.c
  src/config.h
  src/game/game/game.c
  src/game/gameflow.c
  src/game/gameflow.h
  src/game/objects/general/save_crystal.c
  src/game/option/option_passport.c
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/en.json
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/fr.json
  tools/config/Tomb1Main_ConfigTool/Resources/specification.json
Labels: Feature

#972 natla: move facing property to item scope
  CHANGELOG.md
  src/game/items.c
  src/game/objects/creatures/natla.c
  src/global/types.h
Labels: OG bug

#971 gameflow: rework game mode override to match save crystals
  bin/cfg/Tomb1Main_gameflow.json5
  bin/cfg/Tomb1Main_gameflow_ub.json5
  src/game/gameflow.c
  src/game/gameflow.h
  src/game/option/option_passport.c
Labels: Internal

#978 lara: fix responsive jumping delay
  CHANGELOG.md
  src/game/lara/lara_state.c
  src/global/types.h
Labels: T1M bug

#982 gfx: let the player set the fbo filter separately
  CHANGELOG.md
  bin/cfg/Tomb1Main_gameflow.json5
  bin/cfg/Tomb1Main_gameflow_ub.json5
  src/config.c
  src/config.h
  src/game/gameflow.c
  src/game/input.c
  src/game/option/option_graphics.c
  src/gfx/3d/3d_renderer.c
  src/gfx/3d/3d_renderer.h
  src/gfx/common.h
  src/gfx/context.h
  src/gfx/fbo/fbo_renderer.c
  src/gfx/fbo/fbo_renderer.h
  src/global/types.h
  src/specific/s_output.c
Labels: Feature

#983 filesystem: fix heap corruption
  src/specific/s_filesystem.c
  src/specific/s_output.c
Labels: Internal

#991 input: persist toggled settings
  CHANGELOG.md
  src/game/input.c
Labels: Feature

#987 overlay: add 3d pickups animation
  CHANGELOG.md
  src/game/collide.c
  src/game/effects/exploding_death.c
  src/game/inventory/inventory.c
  src/game/lara/lara_hair.c
  src/game/output.c
  src/game/output.h
  src/game/overlay.c
  src/game/overlay.h
  src/game/screen.c
  src/game/viewport.c
  src/game/viewport.h
  src/global/types.h
  src/math/matrix.c
  src/math/matrix.h
  src/specific/s_fmv.c
  src/specific/s_shell.c
Labels: Feature

#994 lara: enable rolling underwater
  CHANGELOG.md
  README.md
  bin/data/lara_animations.bin
  src/config.c
  src/config.h
  src/game/effect_routines/turn_180.c
  src/game/lara/lara_col.c
  src/game/lara/lara_col.h
  src/game/lara/lara_state.c
  src/game/lara/lara_state.h
  src/global/types.h
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/en.json
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/fr.json
  tools/config/Tomb1Main_ConfigTool/Resources/specification.json
Labels: Feature, Data

#1001 ai: make baddies drop ammo if Lara has guns
  CHANGELOG.md
  src/game/objects/creatures/baldy.c
  src/game/objects/creatures/cowboy.c
  src/game/objects/creatures/pierre.c
  src/game/objects/creatures/skate_kid.c
Labels: OG bug

#976 gameflow: add bonus level type
  CHANGELOG.md
  README.md
  bin/cfg/Tomb1Main_gameflow.json5
  bin/cfg/Tomb1Main_gameflow_ub.json5
  src/game/game/game.c
  src/game/gameflow.c
  src/game/option/option_passport.c
  src/game/savegame.h
  src/game/savegame/savegame.c
  src/game/savegame/savegame_bson.c
  src/game/shell.c
  src/game/stats.c
  src/game/stats.h
  src/global/types.h
Labels: Feature

#1005 items: detect mode in animation command SFX
  CHANGELOG.md
  README.md
  bin/data/lara_animations.bin
  src/game/items.c
  src/game/items.h
  src/game/lara/lara.c
  src/global/types.h
Labels: Feature, Data

#1006 items: use animation relative frames
  src/game/effect_routines/lara_effects.c
  src/game/items.c
  src/game/items.h
  src/game/lara/lara.c
  src/game/lara/lara_col.c
  src/game/lara/lara_misc.c
  src/game/lara/lara_state.c
  src/game/objects/creatures/ape.c
  src/game/objects/creatures/bacon_lara.c
  src/game/objects/creatures/baldy.c
  src/game/objects/creatures/centaur.c
  src/game/objects/creatures/cowboy.c
  src/game/objects/creatures/crocodile.c
  src/game/objects/creatures/larson.c
  src/game/objects/creatures/lion.c
  src/game/objects/creatures/pierre.c
  src/game/objects/creatures/raptor.c
  src/game/objects/creatures/rat.c
  src/game/objects/creatures/skate_kid.c
  src/game/objects/creatures/statue.c
  src/game/objects/creatures/torso.c
  src/game/objects/creatures/wolf.c
  src/game/objects/general/pickup.c
  src/game/objects/general/puzzle_hole.c
  src/game/objects/general/scion.c
  src/game/objects/general/switch.c
  src/game/objects/traps/movable_block.c
  src/game/objects/traps/rolling_ball.c
  src/game/objects/traps/spikes.c
  src/game/objects/traps/thors_hammer.c
  src/global/types.h
Labels: Internal

#1012 ai: add configurable item drop behaviour
  CHANGELOG.md
  README.md
  bin/cfg/TR1X_gameflow.json5
  bin/cfg/TR1X_gameflow_ub.json5
  meson.build
  src/game/carrier.c
  src/game/carrier.h
  src/game/creature.c
  src/game/gameflow.c
  src/game/gameflow.h
  src/game/items.c
  src/game/level.c
  src/game/objects/creatures/baldy.c
  src/game/objects/creatures/cowboy.c
  src/game/objects/creatures/mummy.c
  src/game/objects/creatures/pierre.c
  src/game/objects/creatures/skate_kid.c
  src/game/savegame/savegame.c
  src/game/savegame/savegame_bson.c
  src/game/savegame/savegame_legacy.c
  src/game/stats.c
  src/global/types.h
Labels: Feature
