Repository LostArtefacts/TRX, pull requests merged in 2023-08, with the labels that each got.

#436 savegame: save and load current music track and timestamp
  CHANGELOG.md
  README.md
  src/config.c
  src/config.h
  src/game/game/game.c
  src/game/music.c
  src/game/music.h
  src/game/savegame.h
  src/game/savegame/savegame_bson.c
  src/json/json_base.c
  src/json/json_base.h
  src/specific/s_audio.h
  src/specific/s_audio_stream.c
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/en.json
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/es.json
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/fr.json
  tools/config/Tomb1Main_ConfigTool/Resources/specification.json
Labels: Feature

#907 installer: overwrite all essential files
  CHANGELOG.md
  tools/installer/Installer/Controls/InstallSettingsStepControl.xaml
  tools/installer/Installer/Installers/BaseInstallSource.cs
  tools/installer/Installer/Installers/GOGInstallSource.cs
  tools/installer/Installer/Installers/IInstallSource.cs
  tools/installer/Installer/Installers/InstallExecutor.cs
  tools/installer/Installer/Installers/InstallUtils.cs
  tools/installer/Installer/Installers/Tomb1MainInstallSource.cs
  tools/installer/Installer/Installers/TombATIInstallSource.cs
  tools/installer/Installer/Models/InstallSettings.cs
Labels: Feature

#912 lara: fix drop-grab
  CHANGELOG.md
  src/game/lara/lara_state.c
  src/global/const.h
Labels: T1M bug

#910 music: fix saving track timestamps loading tracks after they ended
  src/game/game/game.c
  src/game/level.c
  src/game/music.c
  src/game/music.h
  src/game/savegame/savegame_bson.c
  src/global/types.h
Labels: T1M bug

#913 savegame: bump version to version 3 for new music options
  src/game/savegame.h
  src/game/savegame/savegame_bson.c
Labels: Internal

#905 savegame: add triggered music tracks to the savegame
  CHANGELOG.md
  README.md
  src/config.c
  src/config.h
  src/game/savegame/savegame_bson.c
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/en.json
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/es.json
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/fr.json
  tools/config/Tomb1Main_ConfigTool/Resources/specification.json
Labels: OG bug

#914 Rotate some OG 3D pickups to make more sense
  CHANGELOG.md
  bin/cfg/Tomb1Main_gameflow.json5
  bin/cfg/Tomb1Main_gameflow_ub.json5
  bin/data/cat_itemrots.bin
  bin/data/caves_itemrots.bin
  bin/data/cistern_itemrots.bin
  bin/data/colosseum_itemrots.bin
  bin/data/folly_itemrots.bin
  bin/data/hive_itemrots.bin
  bin/data/midas_itemrots.bin
  bin/data/mines_itemrots.bin
  bin/data/obelisk_itemrots.bin
  bin/data/qualopec_itemrots.bin
  bin/data/sanctuary_itemrots.bin
  bin/data/stronghold_itemrots.bin
  bin/data/tihocan_itemrots.bin
  bin/data/valley_itemrots.bin
  bin/data/vilcabamba_itemrots.bin
  src/config.c
  src/config.h
  src/game/inject.c
  src/game/inject.h
  src/game/objects/common.c
  src/game/objects/general/pickup.c
  src/game/objects/general/scion.c
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/en.json
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/fr.json
  tools/config/Tomb1Main_ConfigTool/Resources/specification.json
Labels: Feature, Data

#916 config: add French title for Fix Bear AI
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/fr.json
Labels: Internal

#917 scion: fix Scion_Collision4 rot restore
  src/game/objects/general/scion.c
Labels: T1M bug

#919 data: allow failed injections
  CHANGELOG.md
  src/game/inject.c
  src/game/inject.h
  src/game/level.c
Labels: Feature

#921 gameflow: ignore legacy sequences
  CHANGELOG.md
  src/game/gameflow.c
  src/global/types.h
Labels: Feature

#925 centaur: fix explosion after re-loading
  CHANGELOG.md
  README.md
  src/game/objects/creatures/statue.c
Labels: OG bug

#933 lara: fix jump-twist interruptions
  CHANGELOG.md
  src/game/lara/lara_state.c
Labels: T1M bug

#935 lara: improve jump-twist input detection
  CHANGELOG.md
  src/game/lara/lara_state.c
Labels: Feature

#937 lara: fix TR2 style walk-run-jump
  CHANGELOG.md
  src/game/lara/lara_state.c
Labels: T1M bug

#936 overlay: fix reset and unbind progress bars in controls menu
  CHANGELOG.md
  src/game/option/option_control.c
  src/game/option/option_graphics.c
  src/game/option/option_passport.c
  src/game/overlay.c
  src/game/overlay.h
  src/game/requester.c
  src/game/screen.c
  src/game/screen.h
  src/game/text.c
Labels: T1M bug

#940 inject: fix non-oneshot music triggers
  CHANGELOG.md
  README.md
  bin/cfg/Tomb1Main_gameflow.json5
  bin/cfg/Tomb1Main_gameflow_ub.json5
  bin/data/atlantis_fd.bin
  bin/data/cat_fd.bin
  bin/data/caves_fd.bin
  bin/data/egypt_fd.bin
  bin/data/folly_fd.bin
  bin/data/hive_fd.bin
  bin/data/mines_fd.bin
  bin/data/obelisk_fd.bin
  bin/data/pyramid_fd.bin
  bin/data/qualopec_fd.bin
  bin/data/sanctuary_fd.bin
  bin/data/stronghold_fd.bin
  src/game/inject.c
  src/global/const.h
Labels: OG bug, Data

#944 inject: add the ability to insert floor data
  CHANGELOG.md
  README.md
  bin/cfg/Tomb1Main_gameflow.json5
  bin/data/tihocan_fd.bin
  src/game/inject.c
Labels: Data

#945 inject: fix trigger types in Khamoon levels
  CHANGELOG.md
  README.md
  bin/cfg/Tomb1Main_gameflow.json5
  bin/data/khamoon_fd.bin
  bin/data/obelisk_fd.bin
Labels: OG bug, Data

#946 inject: fix music trigger setups in Folly
  CHANGELOG.md
  README.md
  bin/data/folly_fd.bin
  src/game/inject.c
Labels: Feature, Data

#948 inject: fix Atlantean Stronghold room portals
  CHANGELOG.md
  README.md
  bin/data/stronghold_fd.bin
  src/game/inject.c
Labels: OG bug, Data

#950 lara: fix automatic slope jump-twists
  src/game/lara/lara_state.c
Labels: T1M bug

#955 camera: fix floor data parsing in trigger refresh
  CHANGELOG.md
  src/game/camera.c
Labels: OG bug
