Repository LostArtefacts/TRX, pull requests merged in 2023-04, with the labels that each got.

#797 overlay: fix FPS, healthbar, and arrows from overlapping
  CHANGELOG.md
  src/game/game/game_pause.c
  src/game/inventory/inventory.c
  src/game/inventory/inventory_ring.c
  src/game/overlay.c
  src/game/overlay.h
  src/game/stats.c
  src/global/types.h
Labels: T1M bug

#799 stats: fix mutating state in getters
  src/game/stats.c
Labels: Internal

#802 lara: add jump-twist animations
  CHANGELOG.md
  README.md
  bin/cfg/Tomb1Main_gameflow.json5
  bin/cfg/Tomb1Main_gameflow_ub.json5
  bin/data/lara_animations.bin
  src/config.c
  src/config.h
  src/game/effect_routines/lara_effects.c
  src/game/inject.c
  src/game/items.c
  src/game/items.h
  src/game/lara/lara.c
  src/game/lara/lara_col.c
  src/game/lara/lara_draw.c
  src/game/lara/lara_hair.c
  src/game/lara/lara_misc.c
  src/game/lara/lara_state.c
  src/game/lara/lara_state.h
  src/game/objects/creatures/bacon_lara.c
  src/game/objects/general/pickup.c
  src/game/objects/general/switch.c
  src/game/objects/traps/rolling_ball.c
  src/game/objects/traps/spikes.c
  src/game/objects/traps/thors_hammer.c
  src/global/types.h
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/en.json
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/es.json
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/fr.json
  tools/config/Tomb1Main_ConfigTool/Resources/specification.json
Labels: Feature, Data

#808 option_control: allow sidestep left and right to be unbound
  CHANGELOG.md
  src/game/option/option_control.c
Labels: Feature

#809 lara: refactor animation enums
  src/game/effect_routines/lara_effects.c
  src/game/gun/gun.c
  src/game/gun/gun_pistols.c
  src/game/gun/gun_rifle.c
  src/game/lara/lara.c
  src/game/lara/lara_col.c
  src/game/lara/lara_misc.c
  src/game/lara/lara_state.c
  src/game/objects/creatures/bacon_lara.c
  src/game/objects/general/pickup.c
  src/game/objects/general/puzzle_hole.c
  src/game/objects/general/scion.c
  src/game/objects/traps/movable_block.c
  src/game/objects/traps/rolling_ball.c
  src/game/objects/traps/spikes.c
  src/game/objects/traps/thors_hammer.c
  src/global/types.h
Labels: Internal

#810 lara: add a cheat to explode Lara like in TR2 and TR3
  CHANGELOG.md
  README.md
  bin/data/lara_animations.bin
  src/game/lara/lara.c
  src/game/lara/lara_cheat.c
  src/game/lara/lara_draw.c
  src/global/types.h
Labels: Feature

#818 sound: pause sounds in the inventory instead of stopping
  CHANGELOG.md
  README.md
  src/game/game/game_pause.c
  src/game/inventory/inventory.c
  src/game/sound.c
  src/game/sound.h
  src/specific/s_audio.h
  src/specific/s_audio_sample.c
Labels: T1M bug
