Repository LostArtefacts/TRX, pull requests merged in 2023-07, with the labels that each got.

#888 items: add common function for taking damage
  src/game/creature.c
  src/game/creature.h
  src/game/gun.h
  src/game/gun/gun_misc.c
  src/game/gun/gun_misc.h
  src/game/items.c
  src/game/items.h
  src/game/lara.h
  src/game/lara/lara.c
  src/game/lara/lara_misc.c
  src/game/objects/creatures/ape.c
  src/game/objects/creatures/bacon_lara.c
  src/game/objects/creatures/bat.c
  src/game/objects/creatures/bear.c
  src/game/objects/creatures/centaur.c
  src/game/objects/creatures/crocodile.c
  src/game/objects/creatures/lion.c
  src/game/objects/creatures/mutant.c
  src/game/objects/creatures/raptor.c
  src/game/objects/creatures/rat.c
  src/game/objects/creatures/torso.c
  src/game/objects/creatures/trex.c
  src/game/objects/creatures/wolf.c
  src/game/objects/effects/body_part.c
  src/game/objects/effects/missile.c
  src/game/objects/traps/dart.c
  src/game/objects/traps/falling_ceiling.c
  src/game/objects/traps/flame.c
  src/game/objects/traps/lava.c
  src/game/objects/traps/lightning_emitter.c
  src/game/objects/traps/pendulum.c
  src/game/objects/traps/teeth_trap.c
  src/global/types.h
Labels: Internal

#890 lara: fix jump-twist state softlock
  CHANGELOG.md
  src/game/lara/lara_col.c
  src/game/lara/lara_col.h
  src/game/lara/lara_state.c
Labels: T1M bug

#894 natla: fix Natla's gun moving while she is in her semi death state
  CHANGELOG.md
  README.md
  src/game/objects/creatures/natla.c
Labels: OG bug

#900 savegame: initialise gym only when present
  CHANGELOG.md
  src/game/savegame/savegame.c
Labels: T1M bug

#903 bear: fix the bear pat attack so it does not miss Lara
  CHANGELOG.md
  README.md
  src/config.c
  src/config.h
  src/game/objects/creatures/bear.c
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/en.json
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/es.json
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/fr.json
  tools/config/Tomb1Main_ConfigTool/Resources/specification.json
Labels: OG bug
