Repository LostArtefacts/TRX, pull requests merged in 2023-12, with the labels that each got.

#1091 missile: test range using components
  CHANGELOG.md
  README.md
  src/game/items.c
  src/game/items.h
  src/game/objects/effects/missile.c
Labels: OG bug

#1093 lara: inject gun data into gym level
  CHANGELOG.md
  bin/cfg/TR1X_gameflow.json5
  bin/data/lara_gym_guns.bin
  src/game/inject.c
Labels: TR1X bug, Data

#1095 midas_touch: restrict vertical range
  CHANGELOG.md
  README.md
  src/game/lara/lara_cheat.c
  src/game/objects/traps/midas_touch.c
Labels: OG bug

#1098 console_cmd: accept "shell(s)" to give shotgun ammo
  CHANGELOG.md
  src/game/console_cmd.c
Labels: Enhancement

#1100 passport: allow restart level in save crystal mode
  CHANGELOG.md
  src/game/game/game.c
  src/game/inventory/inventory.c
  src/game/option/option_passport.c
  src/game/requester.c
  src/global/types.h
Labels: Enhancement

#1107 flame: tie FX to Lara's room when on fire
  CHANGELOG.md
  README.md
  src/game/objects/traps/flame.c
Labels: OG bug

#1109 inventory: fix deselecting passport in locked passport modes
  CHANGELOG.md
  src/game/inventory/inventory.c
Labels: OG bug

#1117 console: fix crash when disabled
  CHANGELOG.md
  src/game/console.c
Labels: TR1X bug

#1118 lightning: fix drawing extra bolts
  CHANGELOG.md
  src/game/objects/traps/lightning_emitter.c
Labels: TR1X bug

#1125 option/passport: fix new game requester
  src/game/option/option_passport.c
Labels: TR1X bug

#1128 s/input: improved menu navigation for gamepad controls
  CHANGELOG.md
  src/game/input.c
  src/game/inventory/inventory.c
  src/game/option/option_control.c
  src/specific/s_input.c
Labels: Enhancement
