Repository LostArtefacts/TRX, pull requests merged in 2023-03, with the labels that each got.

#741 shell: fix a crash when a controller is connected
  CHANGELOG.md
  src/game/shell.c
Labels: T1M bug

#747 Added Spanish localization
  CHANGELOG.md
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/es.json
  tools/config/Tomb1Main_ConfigTool/Tomb1Main_ConfigTool.csproj
Labels: Feature

#757 data: fix Natla's henchmen's textures
  CHANGELOG.md
  README.md
  bin/cfg/Tomb1Main_gameflow.json5
  bin/data/cowboy_textures.bin
  bin/data/kold_textures.bin
  bin/data/skateboardkid_textures.bin
  src/game/inject.c
Labels: OG bug, Data

#759 passport: fix requestor arrow position with high savegame numbers
  CHANGELOG.md
  src/game/option/option_passport.c
Labels: T1M bug

#765 shell: fix a crash when taking a screenshot of an opening FMV
  CHANGELOG.md
  src/game/shell.c
Labels: T1M bug

#768 lara: improve braid control
  CHANGELOG.md
  src/game/lara/lara_hair.c
  src/math/matrix.c
Labels: Feature

#770 lara: turn braid to gold with Midas touch
  CHANGELOG.md
  bin/data/braid.bin
  src/game/lara/lara_hair.c
Labels: T1M bug, Data

#772 tools: launch UB from the config tool
  CHANGELOG.md
  tools/config/Tomb1Main_ConfigTool/Controls/MainWindow.xaml
  tools/config/Tomb1Main_ConfigTool/Models/MainWindowViewModel.cs
  tools/config/Tomb1Main_ConfigTool/Models/Tomb1MainConstants.cs
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/en.json
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/es.json
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/fr.json
  tools/config/Tomb1Main_ConfigTool/Utils/ProcessUtils.cs
Labels: Feature

#773 lara: fix shotgun arm animation
  CHANGELOG.md
  README.md
  src/game/lara/lara_draw.c
Labels: OG bug

#775 const: increase the number of effects from 100 to 1000
  CHANGELOG.md
  src/global/const.h
Labels: Feature

#779 dart: added dart emitters to the savegame
  CHANGELOG.md
  src/game/objects/traps/dart.c
  src/game/savegame/savegame_legacy.c
Labels: OG bug

#776 overlay: change bars to better match PS1 and fix scaling options
  CHANGELOG.md
  src/config.c
  src/game/option/option_control.c
  src/game/option/option_graphics.c
  src/game/option/option_passport.c
  src/game/overlay.c
  src/game/requester.c
  src/game/screen.c
  src/game/screen.h
  src/game/text.c
  src/global/const.h
Labels: Feature

#783 music: fix partial masked triggers killing the ambient track
  CHANGELOG.md
  src/game/music.c
  src/game/music.h
  src/game/room.c
Labels: OG bug

#786 music: allow triggers to kill all music
  CHANGELOG.md
  src/game/room.c
Labels: Feature

#789 music: retain active track during enemy speeches
  CHANGELOG.md
  src/config.c
  src/config.h
  src/game/music.c
  src/game/objects/creatures/skate_kid.c
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/en.json
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/es.json
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/fr.json
  tools/config/Tomb1Main_ConfigTool/Resources/specification.json
Labels: Feature

#790 data: convert Pyramid secret fix to injection format
  CHANGELOG.md
  README.md
  bin/cfg/Tomb1Main_gameflow.json5
  bin/data/backpack.bin
  bin/data/backpack_cut.bin
  bin/data/braid.bin
  bin/data/braid_cut1.bin
  bin/data/braid_cut2_cut4.bin
  bin/data/colosseum_roof.bin
  bin/data/cowboy_textures.bin
  bin/data/kold_textures.bin
  bin/data/larson_gun.bin
  bin/data/pyramid_fd.bin
  bin/data/skateboardkid_textures.bin
  bin/data/uzi_sfx.bin
  src/config.c
  src/config.h
  src/game/gameflow.c
  src/game/inject.c
  src/game/inject.h
  src/game/level.c
  src/global/types.h
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/en.json
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/es.json
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/fr.json
  tools/config/Tomb1Main_ConfigTool/Resources/specification.json
Labels: Data

#792 draw: prevent random draw changes in pause screens
  CHANGELOG.md
  src/game/game/game.c
  src/game/game/game_pause.c
  src/game/inventory/inventory.c
  src/game/objects/traps/lightning_emitter.c
  src/game/random.c
  src/game/stats.c
  src/global/types.h
Labels: T1M bug
