Repository LostArtefacts/TRX, pull requests merged in 2023-01, with the labels that each got.

#690 Removes some unused vars and label.
  src/game/option/option_control_pick.c
  src/game/option/option_graphics.c
  src/gfx/screenshot.c
Labels: Internal

#688 music: add support for multiple file formats.
  CHANGELOG.md
  src/game/music.c
Labels: Feature

#689 s/audio: Get rid of lock/unlock after opening audio device
  src/specific/s_audio.c
Labels: Internal

#691 save_crystal: fix collision pushing Lara through walls
  CHANGELOG.md
  src/game/objects/general/save_crystal.c
Labels: T1M bug

#695 s/shell: Add support for older FFmpeg (support for Windows XP)
  src/specific/s_shell.c
Labels: Internal

#684 src/game/music.c: Unused Music_Stop call in Music_Play
  src/game/music.c
  src/game/objects/creatures/natla.c
  src/game/objects/creatures/skate_kid.c
  src/game/room.c
Labels: Internal

#680 Migrate from wgl_ext to SDL_GL
  meson.build
  src/gfx/context.c
  src/gfx/gl/wgl_ext.c
  src/gfx/gl/wgl_ext.h
  src/specific/s_shell.c
Labels: Internal

#702 gfx: refactor get_extension_support
  src/gfx/context.c
Labels: Internal

#706 passport: fix animation when deselecting
  CHANGELOG.md
  src/game/option/option_passport.c
Labels: T1M bug

#704 mummy: add the mummy to the level kill stats if Lara touches it
  CHANGELOG.md
  src/game/objects/creatures/mummy.c
Labels: OG bug, Feature

#697 savegame: save FX array in numerical order instead of reverse order, fix flame emitter crash
  CHANGELOG.md
  src/game/savegame/savegame_bson.c
Labels: T1M bug

#709 scion: fix Scion 1 respawning on load
  CHANGELOG.md
  README.md
  src/game/objects/general/scion.c
  src/game/savegame/savegame.c
  src/game/savegame/savegame_legacy.c
Labels: OG bug

#711 rat: fix dead voles looking alive when a room's water drains
  CHANGELOG.md
  src/game/objects/creatures/rat.c
Labels: T1M bug

#713 sound: do triggered flip effects even there is no sound
  CHANGELOG.md
  README.md
  src/game/effects.c
  src/game/effects.h
  src/game/game/game.c
  src/game/sound.c
Labels: OG bug

#714 sdl_gl: remove SDL_syswm.h from includes.
  src/gfx/context.c
Labels: Internal

#719 math: Make some tables as const.
  src/math/math.c
Labels: Internal

#718 s/input: remove redundant S_Input_KbdKey()
  src/specific/s_input.c
Labels: Internal

#694 shell: use the return value of snprintf() to save an strlen()
  src/game/shell.c
Labels: Internal

#726 Rename JSON paths to use / instead of \\ separators
  bin/cfg/Tomb1Main_gameflow.json5
  bin/cfg/Tomb1Main_gameflow_ub.json5
Labels: Internal
