Repository LostArtefacts/TRX, pull requests merged in 2023-06, with the labels that each got.

#859 s_shell: detect if a controller is added or removed
  CHANGELOG.md
  src/game/input.c
  src/game/input.h
  src/specific/s_input.c
  src/specific/s_input.h
  src/specific/s_shell.c
Labels: Feature

#860 inventory: fix quick load creating an invalid save
  CHANGELOG.md
  src/game/inventory/inventory.c
Labels: T1M bug

#863 lara: add swing animation cancelling
  CHANGELOG.md
  README.md
  src/config.c
  src/config.h
  src/game/lara/lara_misc.c
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/en.json
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/es.json
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/fr.json
  tools/config/Tomb1Main_ConfigTool/Resources/specification.json
Labels: Feature

#867 skatekid: check AI status before executing control
  CHANGELOG.md
  src/game/objects/creatures/skate_kid.c
Labels: OG bug

#864 lara: add responsive jumping
  CHANGELOG.md
  README.md
  bin/cfg/Tomb1Main_gameflow.json5
  bin/cfg/Tomb1Main_gameflow_ub.json5
  bin/data/lara_jumping.bin
  src/config.c
  src/config.h
  src/game/game/game_demo.c
  src/game/inject.c
  src/game/inject.h
  src/game/lara/lara_state.c
  src/global/types.h
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/en.json
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/es.json
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/fr.json
  tools/config/Tomb1Main_ConfigTool/Resources/specification.json
Labels: Feature, Data

#872 missile: test damage range for overflow
  CHANGELOG.md
  src/game/objects/effects/missile.c
Labels: OG bug

#874 gameflow: add bacon lara anchor sequence
  CHANGELOG.md
  README.md
  bin/cfg/Tomb1Main_gameflow.json5
  src/game/gameflow.c
  src/game/objects/creatures/bacon_lara.c
  src/game/objects/creatures/bacon_lara.h
  src/global/types.h
Labels: Feature

#877 bacon_lara: prevent movement after death
  CHANGELOG.md
  src/game/objects/creatures/bacon_lara.c
Labels: Feature

#884 input: fix holding down up or down to scroll the passport faster
  CHANGELOG.md
  src/game/input.c
Labels: T1M bug
