Repository LostArtefacts/TRX, pull requests merged in 2023-11, with the labels that each got.

#1061 fix: wrong include path
  src/game/overlay.c
Labels: Internal

#1064 inject: add the ability to reposition items
  CHANGELOG.md
  bin/data/tihocan_itemrots.bin
  src/game/inject.c
  src/game/inject.h
Labels: OG bug, Data

#1067 data: restore missing trigger in The Cistern
  CHANGELOG.md
  README.md
  bin/cfg/TR1X_gameflow.json5
  bin/data/cistern_fd.bin
Labels: OG bug, Data

#1072 installer: fix detecting Tomb1Main
  CHANGELOG.md
  tools/installer/Installer/Installers/TR1XInstallSource.cs
Labels: TR1X bug

#1076 docs: fix gameflow usage URLs
  CHANGELOG.md
  bin/cfg/TR1X_gameflow.json5
  bin/cfg/TR1X_gameflow_ub.json5
Labels: TR1X bug

#1075 game: make game status modular
  CHANGELOG.md
  src/game/game.h
  src/game/game/game.c
  src/game/game/game_pause.c
  src/game/gameflow.c
  src/game/inventory/inventory.c
  src/game/inventory/inventory_ring.c
  src/game/objects/traps/lightning_emitter.c
  src/game/overlay.c
  src/game/random.c
  src/game/stats.c
  src/global/types.h
Labels: TR1X bug

#1082 random: advance RNG during game setup
  CHANGELOG.md
  src/game/random.c
Labels: TR1X bug

#1080 movable_block: fix stacking multiple blocks on room portals
  CHANGELOG.md
  README.md
  src/game/objects/traps/movable_block.c
  src/game/room.c
Labels: TR1X bug, Enhancement

#1086 build: add meson option to disable static linking
  meson.build
  meson.options
Labels: Internal
