Repository LostArtefacts/TRX, pull requests merged in 2023-05, with the labels that each got.

#817 lara_look: refactor all looks to use the correct functions
  src/game/lara/lara_look.c
  src/game/lara/lara_look.h
  src/game/lara/lara_state.c
Labels: Internal

#816 lara_look: add inverted look option
  CHANGELOG.md
  README.md
  src/config.c
  src/config.h
  src/game/lara/lara_look.c
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/en.json
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/es.json
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/fr.json
  tools/config/Tomb1Main_ConfigTool/Resources/specification.json
Labels: Feature

#821 creatures: refactor animation switches
  src/game/items.c
  src/game/objects/creatures/ape.c
  src/game/objects/creatures/baldy.c
  src/game/objects/creatures/centaur.c
  src/game/objects/creatures/cowboy.c
  src/game/objects/creatures/crocodile.c
  src/game/objects/creatures/larson.c
  src/game/objects/creatures/lion.c
  src/game/objects/creatures/pierre.c
  src/game/objects/creatures/raptor.c
  src/game/objects/creatures/rat.c
  src/game/objects/creatures/skate_kid.c
  src/game/objects/creatures/statue.c
  src/game/objects/creatures/torso.c
  src/game/objects/creatures/wolf.c
  src/game/objects/traps/rolling_ball.c
Labels: Internal

#825 data: improve injection versioning
  bin/data/backpack.bin
  bin/data/backpack_cut.bin
  bin/data/braid.bin
  bin/data/braid_cut1.bin
  bin/data/braid_cut2_cut4.bin
  bin/data/colosseum_fd.bin
  bin/data/colosseum_roof.bin
  bin/data/cowboy_textures.bin
  bin/data/kold_textures.bin
  bin/data/lara_animations.bin
  bin/data/larson_gun.bin
  bin/data/pyramid_fd.bin
  bin/data/skateboardkid_textures.bin
  bin/data/uzi_sfx.bin
  src/game/inject.c
  src/game/savegame/savegame_bson.c
  src/util.h
Labels: Internal

#822 camera: add a speed option for the manual camera
  CHANGELOG.md
  src/config.c
  src/config.h
  src/game/camera.c
  src/game/camera.h
  src/game/lara/lara.c
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/en.json
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/es.json
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/fr.json
  tools/config/Tomb1Main_ConfigTool/Resources/specification.json
Labels: Feature

#832 room: fix ceiling height miscalculation
  CHANGELOG.md
  README.md
  src/game/room.c
Labels: OG bug

#833 lara_col: fix not jumping off collapsing floors with descent fix
  CHANGELOG.md
  src/game/lara/lara_col.c
Labels: T1M bug

#824 input: add menu specific controls
  CHANGELOG.md
  src/game/game/game_cutscene.c
  src/game/game/game_demo.c
  src/game/input.c
  src/game/input.h
  src/game/inventory/inventory.c
  src/game/option/option.c
  src/game/option/option_compass.c
  src/game/option/option_control.c
  src/game/option/option_control_pick.c
  src/game/option/option_graphics.c
  src/game/option/option_passport.c
  src/game/option/option_sound.c
  src/game/requester.c
  src/game/stats.c
  src/global/types.h
  src/specific/s_fmv.c
  src/specific/s_input.c
Labels: Feature

#838 config: remove obsolete enable_xbox_one_controller option
  src/config.c
  src/config.h
Labels: Internal

#839 option/passport: fix busy loop
  src/game/option/option_passport.c
Labels: Internal

#840 output: fix backdrop image appearing ingame
  src/game/level.c
  src/game/output.c
  src/game/shell.c
  src/specific/s_output.c
Labels: Internal

#842 shell: fix skipping Eidos logo
  CHANGELOG.md
  src/game/gameflow.c
  src/game/shell.c
Labels: Feature

#847 fmv: fix a missing delimiter for .mpeg FMVs
  CHANGELOG.md
  src/game/fmv.c
Labels: T1M bug

#849 lara_state: add jumps when looking and look up/down while hanging
  CHANGELOG.md
  README.md
  src/game/lara/lara_state.c
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/en.json
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/es.json
  tools/config/Tomb1Main_ConfigTool/Resources/Lang/fr.json
Labels: Feature

#846 filesystem: add case insensitive directory and file detection
  CHANGELOG.md
  src/filesystem.c
  src/specific/s_filesystem.c
  src/specific/s_filesystem.h
Labels: Feature
