Repository LostArtefacts/TRX, pull requests merged in 2024-06, with the labels that each got.

#1383 inject: increase Scion collision radius
  CHANGELOG.md
  GAMEFLOW.md
  README.md
  data/ship/cfg/TR1X_gameflow.json5
  data/ship/data/injections/scion_collision.bin
  src/game/inject.c
Labels: OG bug, Priority: medium

#1384 gfx: add wireframe mode
  CHANGELOG.md
  COMMANDS.md
  data/ship/cfg/TR1X_gameflow.json5
  data/ship/cfg/TR1X_gameflow_demo_pc.json5
  data/ship/cfg/TR1X_gameflow_ub.json5
  src/config.h
  src/config_map.c
  src/game/console_cmd.c
  src/game/game_string.def
  src/gfx/3d/3d_renderer.c
  src/gfx/3d/3d_renderer.h
  src/gfx/fbo/fbo_renderer.c
Labels: Feature

#1391 output: fix rendering lightnings
  CHANGELOG.md
  src/game/game/game_draw.c
  src/game/output.c
  src/game/output.h
Labels: TR1X bug, Priority: low
