Repository LostArtefacts/TRX, pull requests merged in 2024-09, with the labels that each got.

#1473 option: fix compass needle resetting
  CHANGELOG.md
  src/game/option/option_compass.c
  src/game/option/option_compass.h
  src/game/phase/phase_inventory.c
Labels: TR1X bug

#1478 gameflow: fix override ignored in some sequences
  CHANGELOG.md
  src/game/gameflow.c
Labels: TR1X bug

#1481 demo: fix console input immediately ending demo
  CHANGELOG.md
  src/game/phase/phase_demo.c
Labels: TR1X bug

#1485 lara/cheat: fix kill cheat not fully killing enemies
  CHANGELOG.md
  src/game/console_cmd.c
  src/game/lara/lara.c
  src/game/lara/lara_cheat.c
  src/global/types.h
Labels: TR1X bug, Priority: high

#1487 Fix teleport command
  CHANGELOG.md
  src/game/console_cmd.c
  src/game/items.c
  src/game/items.h
  src/game/lara/lara_cheat.c
  src/game/lara/lara_cheat.h
  src/math/math_misc.c
  src/math/math_misc.h
Labels: TR1X bug, Priority: high

#1488 output: fix texture edges when bilinear filter off
  CHANGELOG.md
  data/ship/cfg/TR1X_gameflow.json5
  data/ship/cfg/TR1X_gameflow_demo_pc.json5
  data/ship/cfg/TR1X_gameflow_ub.json5
  src/config.h
  src/config_map.def
  src/game/game_string.def
  src/game/option/option_graphics.c
  src/specific/s_output.c
Labels: Enhancement, Priority: medium

#1490 console: fix commands being too available
  CHANGELOG.md
  src/game/console_cmd.c
Labels: TR1X bug, Priority: high

#1496 output: improve vertex movement
  CHANGELOG.md
  README.md
  src/game/inject.c
  src/game/level.c
  src/game/output.c
  src/global/const.h
Labels: Feature

#1497 room: test sector range for Torso boss
  CHANGELOG.md
  README.md
  src/game/room.c
Labels: OG bug, Priority: medium

#1498 inject: add benchmarking
  src/game/inject.c
Labels: Internal, Priority: low

#1501 output: add reflections
  CHANGELOG.md
  README.md
  data/ship/cfg/TR1X_gameflow.json5
  data/ship/cfg/TR1X_gameflow_demo_pc.json5
  data/ship/cfg/TR1X_gameflow_ub.json5
  src/config.h
  src/config_map.def
  src/game/collide.c
  src/game/game/game_draw.c
  src/game/game_string.def
  src/game/lara/lara_hair.c
  src/game/lara/lara_state.c
  src/game/objects/common.c
  src/game/objects/common.h
  src/game/objects/general/save_crystal.c
  src/game/option/option_graphics.c
  src/game/output.c
  src/game/output.h
  src/game/room_draw.c
  src/gfx/3d/3d_renderer.c
  src/gfx/3d/3d_renderer.h
  src/gfx/gl/texture.c
  src/gfx/gl/texture.h
  src/specific/s_output.c
  src/specific/s_output.h
Labels: Enhancement, Priority: medium

#1509 bacon_lara: save animation and custom status
  CHANGELOG.md
  src/game/objects/creatures/bacon_lara.c
  src/game/savegame.h
  src/game/savegame/savegame_bson.c
  src/game/savegame/savegame_legacy.c
Labels: TR1X bug, Priority: high

#1512 output: improve anisotropic filter rendering
  CHANGELOG.md
  src/game/output.c
  src/gfx/3d/3d_renderer.c
  src/gfx/gl/texture.c
Labels: Enhancement

#1519 input: changed target change from look to a new keybind
  CHANGELOG.md
  README.md
  data/ship/cfg/TR1X_gameflow.json5
  data/ship/cfg/TR1X_gameflow_demo_pc.json5
  data/ship/cfg/TR1X_gameflow_ub.json5
  src/game/game_string.def
  src/game/input.c
  src/game/option/option_control.c
  src/global/types.h
  src/specific/s_input.c
Labels: Enhancement, Priority: high

#1517 creature: perform safer conversion of hybrids
  CHANGELOG.md
  src/game/creature.c
  src/game/objects/creatures/skate_kid.c
Labels: OG bug, Priority: medium

#1513 inject: add PS1 crystal data
  CHANGELOG.md
  GAMEFLOW.md
  data/ship/cfg/TR1X_gameflow.json5
  data/ship/data/injections/purple_crystal.bin
  src/config.h
  src/config_map.def
  src/game/inject.c
  tools/config/TR1X_ConfigTool/Resources/Lang/en.json
  tools/config/TR1X_ConfigTool/Resources/Lang/es.json
  tools/config/TR1X_ConfigTool/Resources/Lang/fr.json
  tools/config/TR1X_ConfigTool/Resources/Lang/it.json
  tools/config/TR1X_ConfigTool/Resources/specification.json
Labels: Data, Enhancement, Priority: medium

#1523 console_cmd: prevent teleporting to consumed crystals
  CHANGELOG.md
  src/game/console_cmd.c
Labels: TR1X bug, Priority: medium

#1548 config: react to fov changes
  CHANGELOG.md
  src/config.c
  src/game/viewport.c
Labels: Enhancement

#1550 data: adjust extra head mesh for braid
  CHANGELOG.md
  GAMEFLOW.md
  data/ship/cfg/TR1X_gameflow.json5
  data/ship/data/injections/braid_valley.bin
Labels: TR1X bug, Data, Priority: low
