Repository LostArtefacts/TRX, pull requests merged in 2024-03, with the labels that each got.

#1174 es.json: fix error with Eidos logo skip config option
  CHANGELOG.md
  tools/config/TR1X_ConfigTool/Resources/Lang/es.json
Labels: TR1X bug

#1172 meson: refactor
  meson.build
Labels: Internal

#1176 data: add high quality loading screens and images
  CHANGELOG.md
  GAMEFLOW.md
  README.md
  bin/cfg/TR1X_gameflow.json5
  bin/cfg/TR1X_gameflow_ub.json5
  bin/data/eidospc.png
  bin/data/images/atlantis.webp
  bin/data/images/credits_1.webp
  bin/data/images/credits_2.webp
  bin/data/images/credits_3.webp
  bin/data/images/credits_3_alt.webp
  bin/data/images/credits_ps1.webp
  bin/data/images/credits_ub.webp
  bin/data/images/egypt.webp
  bin/data/images/eidos.webp
  bin/data/images/end.webp
  bin/data/images/greece.webp
  bin/data/images/greece_saturn.webp
  bin/data/images/gym.webp
  bin/data/images/install.webp
  bin/data/images/peru.webp
  bin/data/images/title.webp
  bin/data/images/title_og_alt.webp
  bin/data/images/title_ub.webp
  bin/data/titleh_ub.png
  src/config.h
  src/config_map.c
  src/game/gameflow.c
  src/global/types.h
  tools/config/TR1X_ConfigTool/Resources/Lang/en.json
  tools/config/TR1X_ConfigTool/Resources/Lang/es.json
  tools/config/TR1X_ConfigTool/Resources/Lang/fr.json
  tools/config/TR1X_ConfigTool/Resources/specification.json
  tools/generate_images
  tools/resources/images/atlantis.png
  tools/resources/images/credits_1.png
  tools/resources/images/credits_2.png
  tools/resources/images/credits_3.png
  tools/resources/images/credits_3_alt.png
  tools/resources/images/credits_ps1.png
  tools/resources/images/credits_ub.png
  tools/resources/images/egypt.png
  tools/resources/images/eidos.png
  tools/resources/images/end.png
  tools/resources/images/greece.png
  tools/resources/images/greece_saturn.png
  tools/resources/images/gym.png
  tools/resources/images/install.png
  tools/resources/images/peru.png
  tools/resources/images/title.png
  tools/resources/images/title_og_alt.png
  tools/resources/images/title_ub.png
Labels: Feature, Data

#1179 demo: fix target modes affecting demo
  src/game/game/game_demo.c
Labels: Internal

#1180 inventory: fix option header flashing
  src/game/inventory/inventory_ring.c
  src/game/inventory/inventory_ring.h
  src/game/phase/phase_inventory.c
Labels: TR1X bug

#1182 inventory: fix audio playing briefly when exiting to menu
  src/game/phase/phase_inventory.c
  src/game/phase/phase_pause.c
Labels: TR1X bug

#1184 phase/inventory: fix health bar behavior
  src/game/inventory/inventory_ring.c
  src/game/phase/phase_inventory.c
Labels: Internal

#1188 build: fix mathlibrary build failure
  meson.build
Labels: Internal

#1191 gameflow: fix displaying Eidos logo
  src/game/gameflow.c
Labels: Unreleased

#1204 gun: add ability to move look camera while targeting in combat
  CHANGELOG.md
  README.md
  src/game/gun/gun_pistols.c
  src/game/gun/gun_rifle.c
Labels: Enhancement

#1213 config: fix enemy spelling
  CHANGELOG.md
  README.md
  tools/config/TR1X_ConfigTool/Resources/Lang/en.json
Labels: Internal

#1216 clock: make turbo cheat work both ways
  CHANGELOG.md
  COMMANDS.md
  src/game/clock.c
  src/game/clock.h
  src/game/console_cmd.c
  src/game/shell.c
  src/specific/s_clock.c
  src/specific/s_clock.h
Labels: Enhancement

#1219 types: use better type for Lara's rotations
  src/game/camera.c
  src/game/gun/gun.c
  src/game/gun/gun_misc.c
  src/game/gun/gun_pistols.c
  src/game/gun/gun_rifle.c
  src/game/lara/lara.c
  src/game/lara/lara_cheat.c
  src/game/lara/lara_control.c
  src/game/lara/lara_draw.c
  src/game/lara/lara_hair.c
  src/game/lara/lara_look.c
  src/game/objects/general/pickup.c
  src/game/objects/general/switch.c
  src/game/savegame/savegame_bson.c
  src/game/savegame/savegame_legacy.c
  src/game/sound.c
  src/global/types.h
Labels: Internal

#1221 const: rename FRAMES_PER_SECOND to LOGIC_FPS
  src/game/camera.c
  src/game/effect_routines/flood.c
  src/game/effect_routines/powerup.c
  src/game/effect_routines/sand.c
  src/game/gameflow.c
  src/game/lara/lara_control.c
  src/game/objects/creatures/natla.c
  src/game/objects/general/scion.c
  src/game/objects/general/switch.c
  src/game/option/option_compass.c
  src/game/option/option_control.c
  src/game/overlay.c
  src/game/phase/phase_stats.c
  src/game/room.c
  src/global/const.h
Labels: Internal

#1225 demo: do not rely on FPS
  src/game/gameflow.c
  src/game/gameflow.h
  src/game/phase/phase_inventory.c
Labels: Internal

#1223 data: add PDA model injection
  data/ship/cfg/TR1X_gameflow.json5
  data/ship/cfg/TR1X_gameflow_ub.json5
  data/ship/data/pda_model.bin
Labels: Internal, Data

#1224 build: ignore Python cache
  .gitignore
Labels: Internal

#1230 data: fix stacked cabin in Natla's Mines
  CHANGELOG.md
  README.md
  data/ship/data/mines_fd.bin
Labels: OG bug, Data

#1235 data: fix texture issues
  CHANGELOG.md
  README.md
  data/ship/cfg/TR1X_gameflow.json5
  data/ship/data/atlantis_textures.bin
  data/ship/data/cistern_textures.bin
  data/ship/data/colosseum_textures.bin
  data/ship/data/cut3_textures.bin
  data/ship/data/cut4_textures.bin
  data/ship/data/egypt_textures.bin
  data/ship/data/folly_textures.bin
  data/ship/data/khamoon_textures.bin
  data/ship/data/midas_textures.bin
  data/ship/data/mines_textures.bin
  data/ship/data/obelisk_textures.bin
  data/ship/data/pyramid_textures.bin
  data/ship/data/qualopec_textures.bin
  data/ship/data/sanctuary_textures.bin
  data/ship/data/stronghold_textures.bin
  data/ship/data/tihocan_textures.bin
  data/ship/data/valley_textures.bin
  data/ship/data/vilcabamba_textures.bin
Labels: OG bug, Data
