Repository LostArtefacts/TRX, pull requests merged in 2024-05, with the labels that each got.

#1362 mac: update readme with first run before data copy
  README.md
Labels: Internal

#1367 lara_look: fix upside down frame when looking forward too far
  CHANGELOG.md
  README.md
  src/global/const.h
Labels: OG bug

#1372 overlay: fix FPS counter overlapping the healthbar in demos
  CHANGELOG.md
  src/game/overlay.c
Labels: TR1X bug, Enhancement, Priority: low

#1380 gameflow: add unobtainable secrets property
  CHANGELOG.md
  GAMEFLOW.md
  README.md
  src/game/gameflow.c
  src/game/gameflow.h
  src/game/stats.c
  tools/config/TR1X_ConfigTool/Resources/Lang/en.json
Labels: Enhancement
