Repository LostArtefacts/TRX, pull requests merged in 2024-04, with the labels that each got.

#1246 matrix: fix interpolation
  CHANGELOG.md
  src/math/matrix.c
Labels: TR1X bug

#1250 savegame: fix remember played music always being enabled
  CHANGELOG.md
  src/game/savegame/savegame_bson.c
  tools/config/TR1X_ConfigTool/Resources/Lang/en.json
Labels: TR1X bug

#1248 audio: fix saved timestamp when load current music is enabled
  CHANGELOG.md
  src/specific/s_audio_stream.c
Labels: TR1X bug

#1257 console: improve kill command
  CHANGELOG.md
  COMMANDS.md
  src/game/console_cmd.c
  src/game/items.c
  src/game/items.h
  src/game/lara.h
  src/game/lara/lara.c
  src/game/los.c
  src/game/los.h
  src/game/room.c
  src/game/room.h
Labels: TR1X bug

#1260 config: rewrite saving user input layouts
  CHANGELOG.md
  src/config.c
Labels: Enhancement

#1262 camera: improve underwater check
  CHANGELOG.md
  src/game/camera.c
  src/game/level.c
  src/global/types.h
Labels: OG bug

#1270 inject: fix item creation
  src/game/inject.c
Labels: TR1X bug, Unreleased

#1272 data: fix underwater twist animation
  CHANGELOG.md
  data/ship/data/lara_animations.bin
Labels: TR1X bug, Data

#1276 data: fix underwater twist animation length
  data/ship/data/lara_animations.bin
Labels: TR1X bug, Data

#1280 overlay: keep healthbar visible after resurrection
  src/game/overlay.c
Labels: TR1X bug, Unreleased

#1279 Improve frame structuring
  src/game/camera.c
  src/game/collide.c
  src/game/creature.c
  src/game/effects/exploding_death.c
  src/game/effects/gun.c
  src/game/gun.h
  src/game/gun/gun.c
  src/game/gun/gun_misc.c
  src/game/inject.c
  src/game/inject.h
  src/game/items.c
  src/game/items.h
  src/game/lara/lara.c
  src/game/lara/lara_draw.c
  src/game/lara/lara_draw.h
  src/game/lara/lara_hair.c
  src/game/lara/lara_misc.c
  src/game/level.c
  src/game/level.h
  src/game/objects/common.c
  src/game/objects/creatures/bat.c
  src/game/objects/general/bridge.c
  src/game/objects/general/switch.c
  src/game/objects/traps/lightning_emitter.c
  src/game/output.c
  src/game/output.h
  src/game/overlay.c
  src/game/phase/phase_inventory.c
  src/game/room_draw.c
  src/game/savegame/savegame_bson.c
  src/game/savegame/savegame_legacy.c
  src/global/const.h
  src/global/types.h
  src/global/vars.c
  src/global/vars.h
Labels: Internal

#1281 interpolation: fix hair in high speeds
  src/game/interpolation.c
Labels: TR1X bug, Unreleased

#1267 vars: refactor g_InvChosen and fix Lara saying "No" on save/load
  CHANGELOG.md
  README.md
  src/game/carrier.c
  src/game/game/game.c
  src/game/inventory/inventory.c
  src/game/lara.h
  src/game/lara/lara.c
  src/game/lara/lara_control.c
  src/game/lara/lara_state.c
  src/game/objects/common.c
  src/game/objects/common.h
  src/game/objects/general/keyhole.c
  src/game/objects/general/keyhole.h
  src/game/objects/general/pickup.c
  src/game/objects/general/puzzle_hole.c
  src/game/objects/general/puzzle_hole.h
  src/game/objects/traps/midas_touch.c
  src/game/phase/phase_inventory.c
  src/global/vars.c
  src/global/vars.h
Labels: OG bug

#1282 output: animate room sprites
  CHANGELOG.md
  GAMEFLOW.md
  README.md
  data/ship/cfg/TR1X_gameflow.json5
  data/ship/data/cistern_plants.bin
  src/config.h
  src/config_map.c
  src/game/inject.c
  src/game/level.c
  src/game/output.c
  src/global/types.h
  tools/config/TR1X_ConfigTool/Resources/Lang/en.json
  tools/config/TR1X_ConfigTool/Resources/Lang/es.json
  tools/config/TR1X_ConfigTool/Resources/Lang/fr.json
  tools/config/TR1X_ConfigTool/Resources/Lang/it.json
  tools/config/TR1X_ConfigTool/Resources/specification.json
Labels: Feature

#1288 data: fix Colosseum door animation
  CHANGELOG.md
  data/ship/cfg/TR1X_gameflow.json5
  data/ship/data/colosseum_door.bin
Labels: OG bug, Data

#1286 inventory: fix Lara not saying "no" when using Scion
  CHANGELOG.md
  README.md
  src/game/lara/lara.c
  src/game/phase/phase_inventory.c
Labels: OG bug, Enhancement

#1289 Remove old decompilation documents and tools
  docs/ida_types.h
  docs/ida_variables.txt
  tools/ida_import.py
  tools/update_functions
Labels: Internal

#1294 misc: fix lead bar not having bounds resulting in a crash
  CHANGELOG.md
  src/game/objects/general/misc.c
Labels: TR1X bug

#1292 build: fix bundling mac x86 libraries
  .github/workflows/build_macos.yml
Labels: Internal

#1299 overlay: fix flickering sprite pickups
  CHANGELOG.md
  src/game/objects/common.c
  src/game/overlay.c
Labels: TR1X bug

#1303 level: structure animated textures
  src/game/level.c
  src/game/output.c
  src/global/types.h
  src/global/vars.c
  src/global/vars.h
Labels: Internal

#1307 camera: fix vibrations when teleporting
  CHANGELOG.md
  src/game/camera.c
  src/game/camera.h
  src/game/items.c
Labels: TR1X bug

#1319 console/cmd: write config upon change
  CHANGELOG.md
  src/game/console_cmd.c
Labels: TR1X bug

#1321 clock: save turbo speed across game relaunches
  CHANGELOG.md
  src/config.h
  src/config_map.c
  src/game/clock.c
  src/game/clock.h
Labels: Enhancement

#1315 inventory: animate passport at 60 fps
  CHANGELOG.md
  src/game/interpolation.c
  src/game/inventory/inventory_ring.c
  src/game/inventory/inventory_ring.h
  src/game/inventory/inventory_vars.c
  src/game/objects/common.c
  src/game/objects/common.h
  src/game/phase/phase_cutscene.c
  src/game/phase/phase_demo.c
  src/game/phase/phase_game.c
  src/game/phase/phase_inventory.c
  src/game/phase/phase_pause.c
  src/game/phase/phase_stats.c
  src/global/types.h
Labels: Enhancement

#1323 inventory: fix compass needle speed in 60 FPS
  CHANGELOG.md
  src/game/phase/phase_inventory.c
Labels: TR1X bug

#1325 passport: fix flicker
  src/game/phase/phase_inventory.c
Labels: TR1X bug, Unreleased

#1327 room_draw: include camera target room
  CHANGELOG.md
  src/game/game/game_draw.c
  src/game/room_draw.c
  src/game/room_draw.h
Labels: TR1X bug

#1326 output: fix initial flicker
  CHANGELOG.md
  src/gfx/context.c
Labels: Enhancement

#1331 overlay: support boss-only enemy healthbars
  CHANGELOG.md
  src/config.c
  src/config.h
  src/config_map.c
  src/game/creature.c
  src/game/creature.h
  src/game/objects/common.c
  src/game/objects/common.h
  src/game/overlay.c
  tools/config/TR1X_ConfigTool/Resources/Lang/en.json
  tools/config/TR1X_ConfigTool/Resources/Lang/es.json
  tools/config/TR1X_ConfigTool/Resources/Lang/fr.json
  tools/config/TR1X_ConfigTool/Resources/Lang/it.json
  tools/config/TR1X_ConfigTool/Resources/specification.json
Labels: Enhancement

#1332 effects: enable interpolation for 60 FPS
  CHANGELOG.md
  src/game/effects.c
  src/game/interpolation.c
  src/global/types.h
Labels: Enhancement

#1339 phase/inventory: fix jittery spinout animation in 60 FPS
  src/game/phase/phase_inventory.c
Labels: TR1X bug, Unreleased, Priority: high

#1340 requestor: fix slight delay when moving up or down
  CHANGELOG.md
  src/game/requester.c
Labels: OG bug, Priority: low

#1342 build: make Mac builds faster
  .github/workflows/build_macos.yml
Labels: Internal

#1347 level: fix reading animated textures
  CHANGELOG.md
  src/game/level.c
Labels: TR1X bug
