Repository LostArtefacts/TRX, pull requests merged in 2024-07, with the labels that each got.

#1397 shell: rework gameflow options to fix high numbered savegames
  CHANGELOG.md
  src/game/game.h
  src/game/game/game.c
  src/game/game/game_main_menu.c
  src/game/gameflow.c
  src/game/gameflow.h
  src/game/phase/phase.c
  src/game/phase/phase.h
  src/game/phase/phase_cutscene.c
  src/game/phase/phase_demo.c
  src/game/phase/phase_game.c
  src/game/phase/phase_inventory.c
  src/game/phase/phase_pause.c
  src/game/phase/phase_picture.c
  src/game/phase/phase_stats.c
  src/game/savegame.h
  src/game/savegame/savegame.c
  src/game/shell.c
  src/global/types.h
Labels: TR1X bug, Priority: medium

#1400 output: read vertex buffer size from level
  CHANGELOG.md
  README.md
  src/game/gamebuf.c
  src/game/gamebuf.h
  src/game/level.c
  src/game/output.c
  src/game/output.h
Labels: TR1X bug, Priority: medium

#1402 inventory: fix the console command to change FPS causing demo mode
  CHANGELOG.md
  src/game/phase/phase_inventory.c
Labels: TR1X bug

#1406 readme: clarify macOS installation and update Windows folders
  README.md
Labels: Internal

#1405 docs: document the not-so-green path
  SECRETS.md
Labels: Internal

#1408 text: fix flash rate issues
  CHANGELOG.md
  src/game/console.c
  src/game/text.c
Labels: TR1X bug

#1409 option/sound: fix slow volume adjustment rate
  CHANGELOG.md
  src/game/option/option_sound.c
  src/game/phase/phase_inventory.c
Labels: TR1X bug

#1410 inventory: fix demo timer
  src/game/clock.c
  src/game/phase/phase_inventory.c
Labels: TR1X bug

#1411 installer: use existing installation path
  CHANGELOG.md
  tools/installer/Installer/Installers/BaseInstallSource.cs
  tools/installer/Installer/Installers/InstallExecutor.cs
  tools/installer/Installer/Installers/InstallUtils.cs
  tools/installer/Installer/Installers/TR1XInstallSource.cs
Labels: Enhancement, Priority: medium

#1412 lava: add deadly water feature
  CHANGELOG.md
  README.md
  src/game/objects/traps/lava.c
  src/game/room.c
Labels: Feature, Priority: low

#1416 midas_touch: prevent item duplication
  CHANGELOG.md
  src/game/objects/traps/midas_touch.c
Labels: OG bug

#1414 output: add skybox support
  CHANGELOG.md
  GAMEFLOW.md
  README.md
  data/ship/cfg/TR1X_gameflow.json5
  data/ship/data/injections/colosseum_skybox.bin
  data/ship/data/injections/obelisk_skybox.bin
  data/ship/data/injections/obelisk_textures.bin
  data/ship/data/injections/valley_skybox.bin
  data/ship/data/injections/valley_textures.bin
  docs/showcase/console.webp
  docs/showcase/skybox.jpg
  src/config.h
  src/config_map.def
  src/game/inject.c
  src/game/level.c
  src/game/output.c
  src/game/output.h
  src/game/room_draw.c
  src/global/types.h
  src/specific/s_output.c
  tools/config/TR1X_ConfigTool/Resources/Lang/en.json
  tools/config/TR1X_ConfigTool/Resources/Lang/es.json
  tools/config/TR1X_ConfigTool/Resources/Lang/fr.json
  tools/config/TR1X_ConfigTool/Resources/Lang/it.json
  tools/config/TR1X_ConfigTool/Resources/specification.json
Labels: Feature, Data, Priority: low

#1427 lara: add TR2+ swimming option
  CHANGELOG.md
  README.md
  src/config.h
  src/config_map.def
  src/game/lara/lara_control.c
  src/game/lara/lara_state.c
  src/game/phase/phase_demo.c
  src/global/const.h
  tools/config/TR1X_ConfigTool/Resources/Lang/en.json
  tools/config/TR1X_ConfigTool/Resources/Lang/es.json
  tools/config/TR1X_ConfigTool/Resources/Lang/fr.json
  tools/config/TR1X_ConfigTool/Resources/Lang/it.json
  tools/config/TR1X_ConfigTool/Resources/specification.json
Labels: Feature
