Repository LostArtefacts/TRX, pull requests merged in 2024-08, with the labels that each got.

#1428 room: rename floor info
  src/game/box.c
  src/game/camera.c
  src/game/carrier.c
  src/game/collide.c
  src/game/console_cmd.c
  src/game/creature.c
  src/game/gamebuf.c
  src/game/gamebuf.h
  src/game/inject.c
  src/game/interpolation.c
  src/game/items.c
  src/game/lara/lara_control.c
  src/game/lara/lara_hair.c
  src/game/lara/lara_misc.c
  src/game/lara/lara_state.c
  src/game/level.c
  src/game/los.c
  src/game/lot.c
  src/game/objects/common.c
  src/game/objects/creatures/bacon_lara.c
  src/game/objects/creatures/bat.c
  src/game/objects/creatures/crocodile.c
  src/game/objects/creatures/natla.c
  src/game/objects/creatures/torso.c
  src/game/objects/effects/body_part.c
  src/game/objects/effects/bubble.c
  src/game/objects/effects/missile.c
  src/game/objects/effects/splash.c
  src/game/objects/general/bridge.c
  src/game/objects/general/cog.c
  src/game/objects/general/door.c
  src/game/objects/general/scion.c
  src/game/objects/traps/dart.c
  src/game/objects/traps/falling_block.c
  src/game/objects/traps/lava.c
  src/game/objects/traps/lightning_emitter.c
  src/game/objects/traps/movable_block.c
  src/game/objects/traps/pendulum.c
  src/game/objects/traps/rolling_ball.c
  src/game/objects/traps/sliding_pillar.c
  src/game/objects/traps/thors_hammer.c
  src/game/phase/phase_demo.c
  src/game/room.c
  src/game/room.h
  src/game/savegame/savegame.c
  src/game/stats.c
  src/global/types.h
Labels: Internal, Priority: low

#1429 room: fix tilt being disabled when not on a walkable
  src/game/room.c
Labels: Internal

#1431 room: fix dangling return condition
  src/game/room.c
Labels: Internal

#1430 types: refactor sector floor and ceiling properties
  src/game/carrier.c
  src/game/inject.c
  src/game/items.c
  src/game/level.c
  src/game/objects/general/bridge.c
  src/game/objects/general/bridge.h
  src/game/objects/general/door.c
  src/game/objects/general/trapdoor.c
  src/game/objects/general/trapdoor.h
  src/game/objects/traps/falling_block.c
  src/game/objects/traps/falling_block.h
  src/game/room.c
  src/game/setup.c
  src/global/const.h
  src/global/types.h
Labels: Internal

#1433 room: refactor tilt and portal interpretation
  src/game/carrier.c
  src/game/level.c
  src/game/objects/general/bridge.c
  src/game/objects/general/door.c
  src/game/room.c
  src/game/room.h
  src/global/types.h
Labels: Internal

#1440 config: fix missing Spanish translation option for target lock
  CHANGELOG.md
  tools/config/TR1X_ConfigTool/Resources/Lang/es.json
Labels: TR1X bug, Priority: high

#1441 gun: make rifle code consistent with pistols
  src/game/gun.h
  src/game/gun/gun.c
  src/game/gun/gun_pistols.c
  src/game/gun/gun_pistols.h
  src/game/gun/gun_rifle.c
  src/game/gun/gun_rifle.h
Labels: Internal

#1445 inventory: set any weapon to default on pickup if unarmed
  CHANGELOG.md
  README.md
  src/game/gun.h
  src/game/gun/gun.c
  src/game/inventory/inventory_func.c
Labels: Feature, Priority: low

#1450 gun: fix early hiding of pistol meshes
  CHANGELOG.md
  src/game/gun/gun_pistols.c
Labels: TR1X bug

#1453 room: fix invalid walkable detection
  CHANGELOG.md
  src/game/room.c
Labels: TR1X bug

#1454 types: fix camera data signedness
  CHANGELOG.md
  src/global/types.h
Labels: TR1X bug

#1461 Fix inventory ring shutdown
  CHANGELOG.md
  src/config.c
  src/game/inventory/inventory_ring.c
  src/game/inventory/inventory_ring.h
  src/game/option.h
  src/game/option/option.c
  src/game/option/option_compass.c
  src/game/option/option_compass.h
  src/game/option/option_control.c
  src/game/option/option_control.h
  src/game/option/option_control_pick.c
  src/game/option/option_control_pick.h
  src/game/option/option_graphics.c
  src/game/option/option_graphics.h
  src/game/option/option_passport.c
  src/game/option/option_passport.h
  src/game/option/option_sound.c
  src/game/option/option_sound.h
  src/game/phase/phase_inventory.c
  src/game/requester.c
  src/game/shell.c
Labels: TR1X bug, Priority: medium

#1466 build: build every pull request
  .github/workflows/build_game.yml
  .github/workflows/build_game_macos.yml
  .github/workflows/pr_builds.yml
  .github/workflows/release.yml
Labels: Internal

#1458 level: refactor level loader and introduce benchmarking
  src/game/level.c
  src/game/level.h
Labels: Internal
